### ISSUE TITLE
Error Running Example ord() expected a character, but string of length 0 found

### ISSUE THREAD

**Issue by brettallred** [kineticadb/kinetica-api-python#1]
Trying to run through the python example but I am getting an error when trying to get records.

I am currently running the installed version of aws ami version(https://aws.amazon.com/marketplace/pp/B00PMNLW2K#support)

```
Traceback (most recent call last):
  File "example/example.py", line 204, in <module>
    gpudb_example()
  File "example/example.py", line 67, in gpudb_example
    response = h_db.get_records(table_name=my_table, offset=0, limit=100, encoding='json', options={})
  File "/Users/brett/Code/opensource/kinetica_python/kinetica-api-python-release-v5.2.0/gpudb/gpudb.py", line 2973, in get_records
    return self.post_then_get( REQ_SCHEMA, REP_SCHEMA, obj, '/get/records' )
  File "/Users/brett/Code/opensource/kinetica_python/kinetica-api-python-release-v5.2.0/gpudb/gpudb.py", line 433, in post_then_get
    return self.read_datum(REP_SCHEMA, response, None, response_time)
  File "/Users/brett/Code/opensource/kinetica_python/kinetica-api-python-release-v5.2.0/gpudb/gpudb.py", line 386, in read_datum
    out = self.read_orig_datum(SCHEMA, resp['data'], 'BINARY')
  File "/Users/brett/Code/opensource/kinetica_python/kinetica-api-python-release-v5.2.0/gpudb/gpudb.py", line 352, in read_orig_datum
    out = reader.read(bd) # read, give a decoder
  File "/Users/brett/.pyenv/versions/2.7.13/lib/python2.7/site-packages/avro/io.py", line 445, in read
    return self.read_data(self.writers_schema, self.readers_schema, decoder)
  File "/Users/brett/.pyenv/versions/2.7.13/lib/python2.7/site-packages/avro/io.py", line 490, in read_data
    return self.read_record(writers_schema, readers_schema, decoder)
  File "/Users/brett/.pyenv/versions/2.7.13/lib/python2.7/site-packages/avro/io.py", line 690, in read_record
    field_val = self.read_data(field.type, readers_field.type, decoder)
  File "/Users/brett/.pyenv/versions/2.7.13/lib/python2.7/site-packages/avro/io.py", line 472, in read_data
    return decoder.read_long()
  File "/Users/brett/.pyenv/versions/2.7.13/lib/python2.7/site-packages/avro/io.py", line 184, in read_long
    b = ord(self.read(1))
TypeError: ord() expected a character, but string of length 0 found
```

**Comment by saifrahmed** [comment]
Dear @brettallred Thank you for raising this issue. This was fixed on software version 7.0.0.1. At the moment, we suggest using the latest python bindings (7.1.4.0+) to access a host of new features now available.
https://pypi.org/project/gpudb/#history
