### ISSUE TITLE
pip3 install gpudb==6.2.0.3 fails due to import error

### ISSUE THREAD

**Issue by veloxo** [kineticadb/kinetica-api-python#6]
Installing gpudb 6.2.0.3 to python3.6 (via pip3) gives the following error:
```
Collecting gpudb
  Using cached gpudb-6.2.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2vucd4wd/gpudb/setup.py", line 54, in <module>
        python_dev_path          = distutils.sysconfig.get_python_inc()
    AttributeError: module 'distutils' has no attribute 'sysconfig'
```

This appears to be due to `import distutils` where `import distutils.sysconfig` is necessary.

**Comment by mmahmud** [comment]
Hi @veloxo, thank you for bringing this to our attention.  We've pushed the fix with our latest update.
